-- King Within — Phase 2 schema additions.
-- Safe to run multiple times (idempotent). Run this in the Supabase SQL Editor.

-- 1) Course content columns on `levels`
--    reading_text             -> the Reading Comprehension passage
--    critical_thinking_prompt -> the open reflection prompt
alter table levels add column if not exists reading_text text;
alter table levels add column if not exists critical_thinking_prompt text;

-- 2) Quiz questions. One row per question; options is a JSON array of strings,
--    correct_index is 0-based into that array.
create table if not exists questions (
  id            bigint generated by default as identity primary key,
  level_id      integer not null references levels(level_id) on delete cascade,
  prompt        text not null,
  options       jsonb not null,
  correct_index integer not null,
  sort_order    integer not null default 0
);
create index if not exists questions_level_id_idx on questions (level_id);

-- 3) Quiz score tracking on `user_progress`
--    (the Critical Thinking answer reuses the existing submission_content column)
alter table user_progress add column if not exists quiz_score integer;
alter table user_progress add column if not exists quiz_total integer;

-- 4) Row Level Security: signed-in users can read all questions.
alter table questions enable row level security;
drop policy if exists "questions readable by authenticated" on questions;
create policy "questions readable by authenticated"
  on questions for select
  to authenticated
  using (true);
