-- King Within — Expansion 2 schema: admin CMS, blog library, journal, XP ledger.
-- Run in the Supabase SQL Editor after 01_schema.sql / 02_seed_initiate.sql.
-- Safe to re-run.

-- ---------------------------------------------------------------------------
-- 1) Admin flag + helper used by every "admins can write" RLS policy
-- ---------------------------------------------------------------------------
alter table profiles add column if not exists is_admin boolean not null default false;

create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select coalesce((select is_admin from profiles where id = auth.uid()), false)
$$;

-- ---------------------------------------------------------------------------
-- 2) Blog: themed tracks + posts (markdown body)
-- ---------------------------------------------------------------------------
create table if not exists blog_tracks (
  id          bigint generated by default as identity primary key,
  slug        text unique not null,
  title       text not null,
  description text,
  sort_order  integer not null default 0,
  published   boolean not null default true,
  created_at  timestamptz not null default now()
);

create table if not exists blog_posts (
  id              bigint generated by default as identity primary key,
  slug            text unique not null,
  track_id        bigint references blog_tracks(id) on delete set null,
  order_in_track  integer not null default 0,
  title           text not null,
  excerpt         text,
  body            text,            -- markdown
  category        text,
  reading_minutes integer not null default 3,
  published       boolean not null default false,
  published_at    timestamptz,
  created_at      timestamptz not null default now()
);
create index if not exists blog_posts_track_idx on blog_posts (track_id, order_in_track);

-- ---------------------------------------------------------------------------
-- 3) Journal: question bank + one entry per user per day
-- ---------------------------------------------------------------------------
create table if not exists journal_questions (
  id         bigint generated by default as identity primary key,
  prompt     text not null,
  category   text,
  sort_order integer not null default 0,
  published  boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists journal_entries (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  question_id bigint references journal_questions(id) on delete set null,
  answer_text text,
  free_text   text,
  entry_date  date not null default current_date,
  completed   boolean not null default false,
  created_at  timestamptz not null default now(),
  unique (user_id, entry_date)
);
create index if not exists journal_entries_user_idx on journal_entries (user_id, entry_date);

-- ---------------------------------------------------------------------------
-- 4) XP ledger — every XP gain is an event; profiles.total_xp stays the total
-- ---------------------------------------------------------------------------
create table if not exists xp_events (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users(id) on delete cascade,
  source     text not null check (source in ('course', 'journal')),
  source_ref text,
  amount     integer not null,
  created_at timestamptz not null default now()
);
create index if not exists xp_events_user_idx on xp_events (user_id, created_at);

-- ---------------------------------------------------------------------------
-- 5) RPC: a random published question this user has not seen yet
-- ---------------------------------------------------------------------------
create or replace function public.next_journal_question(uid uuid)
returns setof journal_questions
language sql
stable
set search_path = public
as $$
  select q.* from journal_questions q
  where q.published
    and not exists (
      select 1 from journal_entries e
      where e.user_id = uid and e.question_id = q.id
    )
  order by random()
  limit 1
$$;

-- ---------------------------------------------------------------------------
-- 6) Row Level Security
-- ---------------------------------------------------------------------------
alter table blog_tracks enable row level security;
alter table blog_posts enable row level security;
alter table journal_questions enable row level security;
alter table journal_entries enable row level security;
alter table xp_events enable row level security;

-- Blog: anyone (incl. anon, for SEO/build) reads published; admins do everything
drop policy if exists "blog_tracks read" on blog_tracks;
create policy "blog_tracks read" on blog_tracks for select using (published or public.is_admin());
drop policy if exists "blog_tracks admin" on blog_tracks;
create policy "blog_tracks admin" on blog_tracks for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "blog_posts read" on blog_posts;
create policy "blog_posts read" on blog_posts for select using (published or public.is_admin());
drop policy if exists "blog_posts admin" on blog_posts;
create policy "blog_posts admin" on blog_posts for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Journal questions: signed-in users read published; admins manage
drop policy if exists "journal_questions read" on journal_questions;
create policy "journal_questions read" on journal_questions for select to authenticated using (published or public.is_admin());
drop policy if exists "journal_questions admin" on journal_questions;
create policy "journal_questions admin" on journal_questions for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Per-user owned tables
drop policy if exists "journal_entries own" on journal_entries;
create policy "journal_entries own" on journal_entries for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "xp_events own select" on xp_events;
create policy "xp_events own select" on xp_events for select to authenticated using (user_id = auth.uid());
drop policy if exists "xp_events own insert" on xp_events;
create policy "xp_events own insert" on xp_events for insert to authenticated with check (user_id = auth.uid());

-- Admins can write existing content tables (read policies from 01_schema stay)
drop policy if exists "levels admin" on levels;
create policy "levels admin" on levels for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "questions admin" on questions;
create policy "questions admin" on questions for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- 7) Bootstrap yourself as admin — REPLACE the email with YOUR app login email
-- ---------------------------------------------------------------------------
-- update profiles set is_admin = true where email = 'you@example.com';
