-- King Within — Expansion 4: flexible course "blocks" (Duolingo-style parts).
-- Run in Supabase after the earlier db files. Safe to re-run (only migrates
-- levels that don't yet have any blocks, so it won't clobber hand-authored ones).

create table if not exists course_blocks (
  id         bigint generated by default as identity primary key,
  level_id   integer not null references levels(level_id) on delete cascade,
  sort_order integer not null default 0,
  type       text not null,            -- reading|image|video|audio|writing|quiz|fill_blank|true_false|match
  content    jsonb not null default '{}'::jsonb,
  content_fa jsonb,                     -- Persian mirror; per-field English fallback in the app
  created_at timestamptz not null default now()
);
create index if not exists course_blocks_level_idx on course_blocks (level_id, sort_order);

-- RLS: anyone can read; admins manage.
alter table course_blocks enable row level security;
drop policy if exists "course_blocks read" on course_blocks;
create policy "course_blocks read" on course_blocks for select using (true);
drop policy if exists "course_blocks admin" on course_blocks;
create policy "course_blocks admin" on course_blocks for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- Auto-convert existing courses → blocks (reading, then writing, then quizzes).
-- Only for levels that have no blocks yet.
-- ---------------------------------------------------------------------------
with to_migrate as (
  select l.level_id
  from levels l
  where not exists (select 1 from course_blocks b where b.level_id = l.level_id)
)
insert into course_blocks (level_id, sort_order, type, content, content_fa)
-- reading passage
select l.level_id, 1, 'reading',
       jsonb_build_object('body', l.reading_text),
       case when coalesce(l.reading_text_fa,'') <> '' then jsonb_build_object('body', l.reading_text_fa) end
from levels l join to_migrate m on m.level_id = l.level_id
where coalesce(l.reading_text,'') <> ''
union all
-- critical-thinking writing prompt
select l.level_id, 2, 'writing',
       jsonb_build_object('prompt', l.critical_thinking_prompt),
       case when coalesce(l.critical_thinking_prompt_fa,'') <> '' then jsonb_build_object('prompt', l.critical_thinking_prompt_fa) end
from levels l join to_migrate m on m.level_id = l.level_id
where coalesce(l.critical_thinking_prompt,'') <> ''
union all
-- each quiz question becomes its own block (sorted after reading+writing)
select q.level_id, 2 + q.sort_order, 'quiz',
       jsonb_build_object('prompt', q.prompt, 'options', q.options, 'correct_index', q.correct_index),
       case when coalesce(q.prompt_fa,'') <> '' or q.options_fa is not null
            then jsonb_build_object('prompt', q.prompt_fa, 'options', q.options_fa, 'correct_index', q.correct_index) end
from questions q join to_migrate m on m.level_id = q.level_id;
