-- King Within — capture each individual answer for future AI analysis.
-- One row per answered part (quiz pick, true/false, fill-blank text, writing,
-- match). Reading/video/audio/image parts aren't recorded (no answer).
-- Run in Supabase after the earlier db files. Safe to re-run.

create table if not exists user_answers (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users(id) on delete cascade,
  level_id   integer references levels(level_id) on delete set null,
  block_id   bigint references course_blocks(id) on delete set null,
  type       text not null,           -- quiz | true_false | fill_blank | match | writing
  answer     jsonb,                   -- { value: <their answer> }
  is_correct boolean,                 -- null for non-graded (writing)
  created_at timestamptz not null default now()
);
create index if not exists user_answers_user_idx on user_answers (user_id, created_at);
create index if not exists user_answers_level_idx on user_answers (user_id, level_id);

-- RLS: a user reads/writes only their own answers; admins can read all (for the
-- future AI / personality feature).
alter table user_answers enable row level security;
drop policy if exists "user_answers select" on user_answers;
create policy "user_answers select" on user_answers for select to authenticated
  using (user_id = auth.uid() or public.is_admin());
drop policy if exists "user_answers insert" on user_answers;
create policy "user_answers insert" on user_answers for insert to authenticated
  with check (user_id = auth.uid());
