-- King Within — the Lion AI agent.
-- Stores each insight the Lion produces for a user (personality analysis today,
-- more skills later). Keeping a table (not a single column) preserves history so
-- the user can see how their analysis evolves over time.
-- Run in Supabase after the earlier db files. Safe to re-run.

create table if not exists lion_insights (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users(id) on delete cascade,
  skill      text not null default 'personality',  -- personality | coach | guide | reflection
  locale     text not null default 'en',           -- language the insight was written in
  content    text not null,                         -- the Lion's response
  model      text,                                  -- which model produced it
  created_at timestamptz not null default now()
);
create index if not exists lion_insights_user_idx on lion_insights (user_id, created_at desc);

-- RLS: a user reads/writes only their own insights; admins can read all.
-- The Edge Function runs with the caller's JWT, so these same policies apply
-- to the function's reads and its insert (no service-role key needed).
alter table lion_insights enable row level security;
drop policy if exists "lion_insights select" on lion_insights;
create policy "lion_insights select" on lion_insights for select to authenticated
  using (user_id = auth.uid() or public.is_admin());
drop policy if exists "lion_insights insert" on lion_insights;
create policy "lion_insights insert" on lion_insights for insert to authenticated
  with check (user_id = auth.uid());
