-- King Within — the Lion's 3rd skill: a back-and-forth conversation.
-- Stores each chat turn so the Lion can remember the dialogue across sessions
-- and devices. The Edge Function (running with the caller's JWT) writes both the
-- user turn and the assistant reply; RLS keeps every row owner-only.
-- Run in Supabase after the earlier db files. Safe to re-run.

create table if not exists lion_messages (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users(id) on delete cascade,
  role       text not null check (role in ('user', 'assistant')),
  content    text not null,
  created_at timestamptz not null default now()
);
create index if not exists lion_messages_user_idx on lion_messages (user_id, created_at);

alter table lion_messages enable row level security;
drop policy if exists "lion_messages own" on lion_messages;
create policy "lion_messages own" on lion_messages for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
